using System.Collections.Generic;

namespace TravellerWikiInfomationArticles
{
    public class WikiInformationArticles
    {
        public static List<InformationArticle> Articles = new ()
        {
            new InformationArticle(
                "Equites Ordinis Deorum",
                "The Knights in the Vers Empire who have magic powers and are trained in how to use them. Dating back to the earliest days of the empire, these Knights have worked closely with religious leaders and the Mages Guild to stick around throughout the various transtions of governments. Today the EOD serves the empress directly as their master, due to the requirements set on the EOD by the Sith Order during the Merging of Empires. The Knights are famous for their Orange Armour, Orange Void blades, purple capes with Golden trim, and most recognizable of all are the various tattoos of oaths embroidered on the most devote.",
                new List<InformationSection>()
                {
                    new InformationSection("History",new List<string>()
                    {
                        "### Founding(~3091)\nThe Equites Ordinis Deorum traces its roots to days of the proto-Vers Empire, in the Lordship of Germushia, then held by Lord Troyard. He granted his Knights request to form a study group with several other Knights, Mages from the Guild, and senior people in the Lordships sizeable church. This laid much of the foundation of the EOD, a mix of Magic, Religion, and Knighthood.",
                        "#### First Versian Civil War(~3121)\nWhen then knight Sigmar achieved his title, he joined the EOD, in this same period, the First Empire was forming. One of the reforms brought on by Emperor Alexi Volkov I was granting the Equites Ordinis Orbitalis the ability to confirm new Knights without needing the approval of the emperor. With this change, the number of knights and complexity of Knighthood increased greatly. Sigmar then had a much larger cast of recruits to draw from for his own Order. Once it reached a reasonable size, Sigmar approached the emperor himself to request a _Charter of Rights_ for his Order. An agreement was reached whereby the Equites Ordinis Deorum would have its Charter in exchange for devoted service to the Empire, their Lord, and the emperor, as well as adherence to service to the Mages Guild. Sigmar quickly agreed.",
                        "#### The Three Knights\nCharter in hand, the EOD served a major role in the Versian Civil war, most famously were the three Knights: Resnov, Heidren, and Jarsol who liberated the Asteroid-Barony of Seguel without any other assistance. The mission is said to have begun with the three crashing a stolen tradership into the asteroid-bases shipyard/docks. The trio who had ejected an hour earlier, float through space using minor thruster power and the stations internal gravity system to coast towards it, until they were close enough that they were able to use their combined magic-powers to cast a spell which turned all oxygen within the station into methane, which took effect within moments of the ships impact, destroying the station and the asteroid. *The three were martyred by the super-accelerated debris from the explosion.* In their honour, the **Oath of Debris** was written.",
                        "#### Council of Mages and religious reconciliation (~3349)\nFollowing the First Versian Civil War, the battered and beaten empire limped through recovery. The Lords of the empire grew in strength due to their ability to fund expeditions to nearby Solar Systems using the new Aldnoah Drives. The Lords dispatched their Knights in landing-castles to take the new holdings for the Lords. Once the planets were under a Knights control, the lord often send new Knights to assist the one controlling the world, creating a Knight commander and his fief of knights, who would often be given control over various towns or minor settlements on the new world, or within the system to manage and govern for the Knight or Lord in their absence. ",
                        "Due to this, the number of knights continued to boom. While Sigmar had taken most of the empire’s religious population, and the Mages Guild took many more, those who remained and may eventually be eligible for knighthood had begun to embrace a variety of beliefs. Those on Vers itself most often took up either the Versian Pantheon of the Mages Guild, or the Cult of Sigmar from Pluto. While the pages and squires in systems shared with the Federation often practiced Jedi-ism, and of course any young one is enraptured by the tales of heroic witchers conquering the most fearsome creatures in the dangerous border regions, especially the children of nobles safely locked away in cities with enough protections that many witchers felt safe enough to go weaponless.",
                        "With the two issues in mind: the lack of candidates for knighthood due to the mage’s guild taking viable recruits, and strict requires for members of the Equites Oridinis Deorum to believe in the Versian Pantheon, a Council of High Mages was called.",
                        "Across the rapidly expanding empire, the greatest mages of each of the Regealia’s were summoned by request of the Emperor to Vers. _All_ attended the council. Along with the Mages, many of the greatest Equites dae Ordinis Deorum were asked to join the council. The Emperor made the councils purpose clear: find a way to get more Equites for the Oridinis Deorum. Two solutions were presented, one from the Knights who were present, the other from the Mages.",
                        "The knight’s proposition was to drop the religious requirement for the EOD. It was their order after all, clearly, they should be allowed to set the entrance requirement. The Mages Guild objected, citing that the Equites Oridins **DE**orum was a group whose power came from the God’s of the Mages Guild, and thus it was due to their Charter of Rights that the EOD fell within their realm. ",
                        "The Mages Guild instead offered to find a way to merge the growing and developing Witcher Pantheon with their own, and allow the EOD to study Jedi texts, as their knowledge was supposed to be secular in nature and thus outside the scope of the Mage Guild to regulate. The agreed to accept, but on the condition that members of the Mages Guild who _wanted _ join the EOD in an advisory role, as a librarian, teacher, or other form of academic or assistant, could do so, and in doing so could possibly work their way into a knighthood. This was agreeable to the Mages Guild, and the matter was settled. ",
                        "That agreement saw the birth of Versian Deorism, the dominant religion in the Versian Empire, most devoutly practiced by the Equites Oridinis Deorium. It merges the now ancient Versian Pantheon with the ever-evolving Witcher Pantheon, allowing Sigmoria to have a place, and through a crafty understanding of Jedi/Sith-ism has allowed for those religions to join as well. Effectively, Deorism is a hodgepodge of various religious that have brewed together out of necessity, and the groundwork for that brew was laid in the above deal. ",
                        "#### The Third AI War and the Knight Kenrus’ (~3363)\nThe Third AI War is perhaps the most famous war in all of human history. Its age means many have learned of its. Its political, social, economic, scientific, and other effects are incalculable. As a result of this war, humanity for the first time, across all major powers, agreed to outlaw the development of advanced, sentient, artificial intelligence. While it has  of course been broken more times then one can count, it serves as the foundation of anti-AI legislation in every major power in Universalis Confederation. It is thus no surprised that the Equites Ordinis Deorum played a vital role in this war. ",
                        "Overall, The Vers Empire was outside the reach of worst parts of the war (it was instead much more harmed during the first and second AI wars), but Vers itself was always at risk due to its proximity to Terra. The only time during the First Empire in which Equites dae Luna (EDL) landed on Vers was when a suspected Zalyn was thought to have infiltrated the House of Wagnar, posing as its Lord. Working with the EOD, the EDL was able to track down the false person and remove them before they could pose a real threat to Vers or Terra.",
                        "One of the most remarkable stories from the Third AI War for the EOD is that of Knight Kenrus’. Kenrus’ had been born in the Empire, but his family had heritage back to the Lordship of Germushia and were practicing Sigmarians. Kenrus’ had gained his knightly title fighting against a xeno’s invasion for his Lord – he had snatched the lords void-blade and charged head long at three of the elite-warrior class aliens, drawing on instincts he had not known he had, with lighting speed he struck down all three of the warriors, then returning the blade to its proper owner and apologizing for his abrupt usurpation of weapon. The Lord agreed to allow it on the Condition that Kenrus’ take up a knight hood. As word of his deed spread, Kenrus’ was invited to trail for the EOD, and soon joined in full.",
                        "During the Third AI War, before the Empire itself joined the war in proper form, Kenrus’ returned to the lands which had once been colonized by the Lordship of Germushia. The planet Rovterras was under Zalyn Siege, and Kenrus’ had joined a Sigmar battle barge on route to the word, and led the ground assault due to the absence of a proper light-seer. Marching with the Sigmarians into battle, Kenrus’ loudly recited the Versian variant of the Sigmarist Battle Hymn to the rhythm of shot from his pistol and strikes of his sword while the Sigmarians recounted their own hymn to the sounds of their own Ming-Corp™  rifle fire. After Kenrus’ finished using his powers to free a bunker of children under a school which had been trapped by rubble from Zalyn bombings, he heard from one of the teachers of survivors held up in a Sigmarist Temple not far away. Ordering his Sigmarine troops to remain, Kenru’s rushed to save the trapped people from the encroaching Zalyns.",
                        "He arrived not a moment too soon, as the last of the Light-Seers seemed to be on the loosing end of Sigmorias Gaze. The Zalyns heavy weapons were pounding the Void-bubble protecting the temple and the civilians within, its casters aged a year a minute. Kenrus’ used his pistol to stop ten of the Zalyn, but far too many remained. While using his blade to defend himself, Kenrus’ called on Sigmar and the Pantheon of other gods and used the training the Mages had given him to bring forth an army of angles, the bits of the shattered gods which Sigmar had been able to salvage, who repelled the demoness machines.",
                        "Kenrus’ would live through the whole war, after previous story, he would go on to liberate several dozen systems from the Zalyns before the Versian Vanguard arrived. He was part of the party who defeated the final Zalyns, scattering what was left deep into hiding. For his fame in the post war world, he became a Knight-Commander, and eventually gained the title of Lord in the Reverse Galaxy. Unfortunately the title would die out during the First Republic Period, but Knight Kenrus’ legacy lives on within the EOD.",
                        "### Second Empire ~4891\nDuring the Second Empire period the role of Versian Knight Changed greatly, as such, the EOD was forced to adapt to the new reality. The largest change was the shift back to allowing free or unlanded Knights again. This allowed for the ranks of the Knights to swell in size once again, and the EOD to gain its pick of members. However, this new period came with many changes, as the growth of knights and the empire as a whole required the restructuring of Knightly society, and acceptance of larger religious changes; namely the newfound dominance of Witcherism among the nobility.  ",
                        "#### Witcher Expansion and religious Changes ~4391-8391\nFollowing the rise of the First Terran Empire, the Witcher Order took control of the Milky Way Galaxy, and the governments of the major powers were forced to flee with them. The EOD itself was split, as it technically had service to the Lords, but it really had been a tool of the Emperor. As such, the EOD properly continued with the Versian Empire as it fled, while in the Milky Way the EOD became another branch of the Witcher Order, a title held by those Witchers who had been put in charge of Versian worlds.",
                        "As such, when the empire returned and retook their lands from the Witchers, the EOD was easily able to return to its spot, and many were willing to welcome back a non-Witcher source of magic education. In the waning days of the First Empire, the EOD had grown staunchly anti-witcher, relying heavily on its Versian Pantheon.",
                        "That changed moments after the First Empire died with its Emperor, and the Second was crowned by a Witcher believing, civis-born, wrongfully promoted knight who had usurped the Emperor for his position, and seemed to have great support in doing so! The EOD was left with little choice but swear allegiance to the new emperor and hope for the best.",
                        "Rather then mess with a good thing, the emperor left the EOD be for the most part, besides requiring that the Witcher pantheon be brought in line and that its names be used as the primary name for the gods. These minor changes left the EOD in a new position, but the changes the new emperor made to the Knighthood were of much larger benefit to the EOD.",
                        "#### Reorganizing the Knighthood ~4891\nThe new emperors reorganization of the Knighthood mostly involved the reintroduction of Free-Knights, meaning anyone whom the Ordered allowed to become a Knight could become one. This resulted in a large boom in the number of Knights, and as such the EOD’s ranks began to swell.",
                        "Within the Empire, the emperor ordered knew knightly titles be drawn up, setting down the current ranks of the Versian Knights: Page, Squire, Knight, Knight Sergeant, Knight Lieutenant, Master Knight, Knight Captain, Knight Commander. As well as granting many Charters of Rights to new orders. However, the EOD remained the sole organization for Knights of any religion who wished to refine their beliefs or magic into a battlefield artform.",
                        "",
                        "",

                    }),
                    new InformationSection("Order Beliefs",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Major Oaths",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Schools of Magic",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Relation to other Orders",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Relation to Other Guilds",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Standing in Versian Society",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Notable Members",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Important Points",new List<string>()
                    {
                        ""
                    }),
                }),
        };
    }
}