using System.Collections.Generic;

namespace TravellerWikiInfomationArticles
{
    public class WikiInformationArticles
    {
        public static List<InformationArticle> Articles = new ()
        {
            new InformationArticle(
                "Equites Ordinis Deorum",
                "The Knights in the Vers Empire who have magic powers and are trained in how to use them. Dating back to the earliest days of the empire, these Knights have worked closely with religious leaders and the Mages Guild to stick around throughout the various transtions of governments. Today the EOD serves the empress directly as their master, due to the requirements set on the EOD by the Sith Order during the Merging of Empires. The Knights are famous for their Orange Armour, Orange Void blades, purple capes with Golden trim, and most recognizable of all are the various tattoos of oaths embroidered on the most devote.",
                new List<InformationSection>()
                {
                    new InformationSection("History",new List<string>()
                    {
                        "### Founding(~3091)\nThe Equites Ordinis Deorum traces its roots to days of the proto-Vers Empire, in the Lordship of Germushia, then held by Lord Troyard. He granted his Knights request to form a study group with several other Knights, Mages from the Guild, and senior people in the Lordships sizeable church. This laid much of the foundation of the EOD, a mix of Magic, Religion, and Knighthood.",
                        "#### First Versian Civil War(~3121)\nWhen then knight Sigmar achieved his title, he joined the EOD, in this same period, the First Empire was forming. One of the reforms brought on by Emperor Alexi Volkov I was granting the Equites Ordinis Orbitalis the ability to confirm new Knights without needing the approval of the emperor. With this change, the number of knights and complexity of Knighthood increased greatly. Sigmar then had a much larger cast of recruits to draw from for his own Order. Once it reached a reasonable size, Sigmar approached the emperor himself to request a _Charter of Rights_ for his Order. An agreement was reached whereby the Equites Ordinis Deorum would have its Charter in exchange for devoted service to the Empire, their Lord, and the emperor, as well as adherence to service to the Mages Guild. Sigmar quickly agreed.",
                        "#### The Three Knights\nCharter in hand, the EOD served a major role in the Versian Civil war, most famously were the three Knights: Resnov, Heidren, and Jarsol who liberated the Asteroid-Barony of Seguel without any other assistance. The mission is said to have begun with the three crashing a stolen tradership into the asteroid-bases shipyard/docks. The trio who had ejected an hour earlier, float through space using minor thruster power and the stations internal gravity system to coast towards it, until they were close enough that they were able to use their combined magic-powers to cast a spell which turned all oxygen within the station into methane, which took effect within moments of the ships impact, destroying the station and the asteroid. *The three were martyred by the super-accelerated debris from the explosion.* In their honour, the **Oath of Debris** was written.",
                        "#### Council of Mages and religious reconciliation (~3349)\nFollowing the First Versian Civil War, the battered and beaten empire limped through recovery. The Lords of the empire grew in strength due to their ability to fund expeditions to nearby Solar Systems using the new Aldnoah Drives. The Lords dispatched their Knights in landing-castles to take the new holdings for the Lords. Once the planets were under a Knights control, the lord often send new Knights to assist the one controlling the world, creating a Knight commander and his fief of knights, who would often be given control over various towns or minor settlements on the new world, or within the system to manage and govern for the Knight or Lord in their absence. ",
                        "Due to this, the number of knights continued to boom. While Sigmar had taken most of the empire’s religious population, and the Mages Guild took many more, those who remained and may eventually be eligible for knighthood had begun to embrace a variety of beliefs. Those on Vers itself most often took up either the Versian Pantheon of the Mages Guild, or the Cult of Sigmar from Pluto. While the pages and squires in systems shared with the Federation often practiced Jedi-ism, and of course any young one is enraptured by the tales of heroic witchers conquering the most fearsome creatures in the dangerous border regions, especially the children of nobles safely locked away in cities with enough protections that many witchers felt safe enough to go weaponless.",
                        "With the two issues in mind: the lack of candidates for knighthood due to the mage’s guild taking viable recruits, and strict requires for members of the Equites Oridinis Deorum to believe in the Versian Pantheon, a Council of High Mages was called.",
                        "Across the rapidly expanding empire, the greatest mages of each of the Regealia’s were summoned by request of the Emperor to Vers. _All_ attended the council. Along with the Mages, many of the greatest Equites dae Ordinis Deorum were asked to join the council. The Emperor made the councils purpose clear: find a way to get more Equites for the Oridinis Deorum. Two solutions were presented, one from the Knights who were present, the other from the Mages.",
                        "The knight’s proposition was to drop the religious requirement for the EOD. It was their order after all, clearly, they should be allowed to set the entrance requirement. The Mages Guild objected, citing that the Equites Oridins **DE**orum was a group whose power came from the God’s of the Mages Guild, and thus it was due to their Charter of Rights that the EOD fell within their realm. ",
                        "The Mages Guild instead offered to find a way to merge the growing and developing Witcher Pantheon with their own, and allow the EOD to study Jedi texts, as their knowledge was supposed to be secular in nature and thus outside the scope of the Mage Guild to regulate. The agreed to accept, but on the condition that members of the Mages Guild who _wanted _ join the EOD in an advisory role, as a librarian, teacher, or other form of academic or assistant, could do so, and in doing so could possibly work their way into a knighthood. This was agreeable to the Mages Guild, and the matter was settled. ",
                        "That agreement saw the birth of Versian Deorism, the dominant religion in the Versian Empire, most devoutly practiced by the Equites Oridinis Deorium. It merges the now ancient Versian Pantheon with the ever-evolving Witcher Pantheon, allowing Sigmoria to have a place, and through a crafty understanding of Jedi/Sith-ism has allowed for those religions to join as well. Effectively, Deorism is a hodgepodge of various religious that have brewed together out of necessity, and the groundwork for that brew was laid in the above deal. ",
                        "#### The Third AI War and the Knight Kenrus’ (~3363)\nThe Third AI War is perhaps the most famous war in all of human history. Its age means many have learned of its. Its political, social, economic, scientific, and other effects are incalculable. As a result of this war, humanity for the first time, across all major powers, agreed to outlaw the development of advanced, sentient, artificial intelligence. While it has  of course been broken more times then one can count, it serves as the foundation of anti-AI legislation in every major power in Universalis Confederation. It is thus no surprised that the Equites Ordinis Deorum played a vital role in this war. ",
                        "Overall, The Vers Empire was outside the reach of worst parts of the war (it was instead much more harmed during the first and second AI wars), but Vers itself was always at risk due to its proximity to Terra. The only time during the First Empire in which Equites dae Luna (EDL) landed on Vers was when a suspected Zalyn was thought to have infiltrated the House of Wagnar, posing as its Lord. Working with the EOD, the EDL was able to track down the false person and remove them before they could pose a real threat to Vers or Terra.",
                        "One of the most remarkable stories from the Third AI War for the EOD is that of Knight Kenrus’. Kenrus’ had been born in the Empire, but his family had heritage back to the Lordship of Germushia and were practicing Sigmarians. Kenrus’ had gained his knightly title fighting against a xeno’s invasion for his Lord – he had snatched the lords void-blade and charged head long at three of the elite-warrior class aliens, drawing on instincts he had not known he had, with lighting speed he struck down all three of the warriors, then returning the blade to its proper owner and apologizing for his abrupt usurpation of weapon. The Lord agreed to allow it on the Condition that Kenrus’ take up a knight hood. As word of his deed spread, Kenrus’ was invited to trail for the EOD, and soon joined in full.",
                        "During the Third AI War, before the Empire itself joined the war in proper form, Kenrus’ returned to the lands which had once been colonized by the Lordship of Germushia. The planet Rovterras was under Zalyn Siege, and Kenrus’ had joined a Sigmar battle barge on route to the word, and led the ground assault due to the absence of a proper light-seer. Marching with the Sigmarians into battle, Kenrus’ loudly recited the Versian variant of the Sigmarist Battle Hymn to the rhythm of shot from his pistol and strikes of his sword while the Sigmarians recounted their own hymn to the sounds of their own Ming-Corp™  rifle fire. After Kenrus’ finished using his powers to free a bunker of children under a school which had been trapped by rubble from Zalyn bombings, he heard from one of the teachers of survivors held up in a Sigmarist Temple not far away. Ordering his Sigmarine troops to remain, Kenru’s rushed to save the trapped people from the encroaching Zalyns.",
                        "He arrived not a moment too soon, as the last of the Light-Seers seemed to be on the loosing end of Sigmorias Gaze. The Zalyns heavy weapons were pounding the Void-bubble protecting the temple and the civilians within, its casters aged a year a minute. Kenrus’ used his pistol to stop ten of the Zalyn, but far too many remained. While using his blade to defend himself, Kenrus’ called on Sigmar and the Pantheon of other gods and used the training the Mages had given him to bring forth an army of angles, the bits of the shattered gods which Sigmar had been able to salvage, who repelled the demoness machines.",
                        "Kenrus’ would live through the whole war, after previous story, he would go on to liberate several dozen systems from the Zalyns before the Versian Vanguard arrived. He was part of the party who defeated the final Zalyns, scattering what was left deep into hiding. For his fame in the post war world, he became a Knight-Commander, and eventually gained the title of Lord in the Reverse Galaxy. Unfortunately the title would die out during the First Republic Period, but Knight Kenrus’ legacy lives on within the EOD.",
                        "### Second Empire ~4891\nDuring the Second Empire period the role of Versian Knight Changed greatly, as such, the EOD was forced to adapt to the new reality. The largest change was the shift back to allowing free or unlanded Knights again. This allowed for the ranks of the Knights to swell in size once again, and the EOD to gain its pick of members. However, this new period came with many changes, as the growth of knights and the empire as a whole required the restructuring of Knightly society, and acceptance of larger religious changes; namely the newfound dominance of Witcherism among the nobility.  ",
                        "#### Witcher Expansion and religious Changes ~4391-8391\nFollowing the rise of the First Terran Empire, the Witcher Order took control of the Milky Way Galaxy, and the governments of the major powers were forced to flee with them. The EOD itself was split, as it technically had service to the Lords, but it really had been a tool of the Emperor. As such, the EOD properly continued with the Versian Empire as it fled, while in the Milky Way the EOD became another branch of the Witcher Order, a title held by those Witchers who had been put in charge of Versian worlds.",
                        "As such, when the empire returned and retook their lands from the Witchers, the EOD was easily able to return to its spot, and many were willing to welcome back a non-Witcher source of magic education. In the waning days of the First Empire, the EOD had grown staunchly anti-witcher, relying heavily on its Versian Pantheon.",
                        "That changed moments after the First Empire died with its Emperor, and the Second was crowned by a Witcher believing, civis-born, wrongfully promoted knight who had usurped the Emperor for his position, and seemed to have great support in doing so! The EOD was left with little choice but swear allegiance to the new emperor and hope for the best.",
                        "Rather then mess with a good thing, the emperor left the EOD be for the most part, besides requiring that the Witcher pantheon be brought in line and that its names be used as the primary name for the gods. These minor changes left the EOD in a new position, but the changes the new emperor made to the Knighthood were of much larger benefit to the EOD.",
                        "#### Reorganizing the Knighthood ~4891\nThe new emperors reorganization of the Knighthood mostly involved the reintroduction of Free-Knights, meaning anyone whom the Ordered allowed to become a Knight could become one. This resulted in a large boom in the number of Knights, and as such the EOD’s ranks began to swell.",
                        "Within the Empire, the emperor ordered knew knightly titles be drawn up, setting down the current ranks of the Versian Knights: Page, Squire, Knight, Knight Sergeant, Knight Lieutenant, Master Knight, Knight Captain, Knight Commander. As well as granting many Charters of Rights to new orders. However, the EOD remained the sole organization for Knights of any religion who wished to refine their beliefs or magic into a battlefield artform.",
                        "#### Mages Guild War / The Life of Knight Janus ~26528\nA pivotal moment in Versian history, The Mages Guild War was a the result of the two competing Mages Guilds disagreements growing continuously more heated. The Versian Mages Guild was the smaller of the two, with most of its members in the ‘old world’ Milky Way Galaxy. The majority of the Versian Mages Guild’s members were that of the Equites Ordinis Deorum, and the Pre-Witcher Lords. The Witcher’s Mages Guild had more mages in it, and most of the Second Empire’s Lords supported it, as well as the Emperor.",
                        "The War initially simmered as small, mostly verbal, conflicts between members of their respective guilds. Many Lords began to openly pick sides and deny the other entrance into their lands, which was considered a violation of Versian Law and the Guilds’ rights.",
                        "When appealed to the Emperor, he declined to intervene, saying that the Charter of Rights only allows for there to be one Mages Guild, and so while there may be two factions, it is within a Lords right to favour one internal faction over another. Members of the Witchers Guild found this unacceptable, and decided to demonstrate their perceived insanity of the ruling by purging their Guild Halls and Worlds of Versian members, banning there entrance to Witcher aligned worlds. And with that, the battle lines were drawn, and the war began.",
                        "Mages need not use starships to travel between nearby system; a large enough cohort of Mages may simply choose to tunnel through the void themselves and travel to another world. This is often how the most destructive battles of the war began. Mages quickly shifted up in the scale of objects they hurled at one another. Starting with stones, to cars, shuttles, ships, buildings, then escalating to: asteroids, moons, planets and eventually suns. The destruction of this war was enormous, across both galaxies in which the empire operated.",
                        "The Emperor was forced to intervene, but struggled deeply between listening to the majority of Lords and their Godly Knights, or his heart, the minority of lords and the temporal knights. His initial solution was a failure: use the EOD as a strike force to fight against Mages battles where they occur, regardless of who started it, and without favour to either side. The failure of this plan came quickly, as mages would move, fight, and move on long before the EOD with their ships and personnel could be called, raised, and arrive. Lords soon shifted to personally instructed the EOD to lead local taskforces to knights to hunt down and purge any Guildhall who failed to swear fealty to the Lord above all and sign away their right to carry arms or commit violence.",
                        "The Emperor, not wanting to appear disempowered, finally issued a decree ordering the EOD to support the Versian faction of the Mages Guild, but if any Witcher faction whished to remain and laid down their arms to do so, they would be offered protection in the Versian Guild.",
                        "The EOD was not without worry in this regard, as the story of the Life of the Knight Janus tells. Janus had spent most of the war watching over a series of systems with a group of knights he was training and had negotiated a settled peace between the Witcher and Versian factions within.",
                        "This was disrupted however when his lord took the mattes of the war into his own hands, and order Janus to remove the Versian Mages, spitting that they were heretical, backwards vermin not even deserving of worship in the Godly Versarians triangular Churches. Janus gathered his Knights and complied with the order. Sending a Page ahead of his journeys, carrying a message.",
                        "By the time the Knight’s arrived to purge the Guildhalls, they found empty chambers, libraries without books, and no hint as to where its members may have gone. Within a few days Janus received word that the Witcher Guilds had recently had a large influx of new members.",
                        "When Janus received the word from the Order that the Emperor had commanded the protection of the Versian Mages, Janus dispatched the same pages to the Witcher Halls to tell them of the news. Within a few weeks, Janus was informed that the lost Versian Guildsman had been discovered, and that those same guildsmen now controlled the Witchers Halls! _Janus was executed by his Lord for failing to properly see through the Lords commandment; misreporting success to his lordship; and failure to enforce the emperors will.",
                        "#### Sigmarism bend, Failing to stop a Crusade ~34895\nWhile the Germushian Empire was facing internal collapse, a mad ruler who was hated by his people, the Church of Sigmar was vying for power and autonomy from the Germushian State. At the same moment, the _Dicollossius dae Vetparis_ (the local legislative body), decreed that Church of Sigmar was actually part of the Versian Empire, and attempted to merge the ideological beliefs of the Church into the empire. This was considered a great spiritual and legal wrong by the Church, who decreed the Empire heretical, its government heretical, and any who joined its so-called church heretics. It then called on all good servants of Sigmar to join the Sigmarines, Inquisition, and Light-Seers of the Germushian Church in a great Crusade to liberate the true believers trapped under this flagrant violation of Sigmarist belief.",
                        "While the Church rallied troops from across the Milky Way, garnering great support from every major nation besides one: Vers, who had instead become the target of trillions of newly found Siginf and their Sigmarine betters. For the Mages Guild, who were already having to deal with the physical threat posed by the Light-Seers and Librarians of the Church, they also had to navigate merging the new Verisan-Sigmarist religion, Lightseers, believers, and ideas into their Guild and its teachings.",
                        "For the Knights of the EOD, they were attempting to merge the beliefs in their Lord as a supreme deity, with their legal obligation to defend their Lord from invasion as was currently underway by the Church’s forces, and also navigate its legal obligation to assist the Mages Guild, who was undergoing the same Church reforms, and who if the EOD deviated to far from, could become the enemy of the EOD.s",
                        "The Crusade itself can be best described as a great victory for the Church. In the earliest days of the Crusade, the EOD were dispatched to various Churches throughout the area who refused to convert to Versian Sigmarism. The churches were either forced to convert, entered into an armed standoff between the congregation and the Knight, or were outright destroyed – in one particularly notable case, a knight who had previously been a devote Germushian Sigmarist, called upon his Lord as a conduit to Sigmar to smite down the impure house before him, then using his own powers to bring forth a bolt of Void Energy leaving only a crater where once the church sat. Such harsh actions only further riled those who believed in Sigmarism throughout the Galaxy and affirmed the justness of their crusade.",
                        "The second stage of the Crusade went worse then the first. The Empire lost 65% of its land, hundreds of trillions of dead civis, billions of dead soldiers across countless worlds. The empire lost more ships, military and civil personal, and territory then it had in all the wars it had fought that millennium, and the previous two, combined. The Empire EOD fought valiantly, but even the reforms which had previously swelled its ranks were not enough to feed it. The New empire in Reverse had much higher membership, and they hadn’t even heard of the (official only) proposed merging of Sigmarism yet, let alone had their Collosius confirm it.",
                        "The EOD suffered major losses in its own right, severely depleted in the Galaxy, they had abandoned the goal of defending Churches and other religious buildings, with most Knights returning to fiefs if they had, otherwise assisting their fellow knights in keeping hold of their fiefs. Unity among the Lords and Knights had been broken. The crusade was an unstoppable wave which would obliterate all in its path, the best any knight could hope for was to shelter the storm without loosing everything.",
                        "The third phase of the crusade started off appearing better for the Empire then the previous had. The Emperor had arrived in the Galaxy with several lords and a majority of their Knights in tow. However, the reinforcements quickly became depleted, and the Lords grew defiant when they learned the circumstances behind the war, and the emperors stubborn unwillingness to concede his unofficially granted title back to the Church. Instead, he wasted countless more lives attempting to hold on to an ever-shrinking amount of land.",
                        "Eventually it was too late, the emperor could not  deny that he was loosing, and under pressure from both the Lords he had brought with him, and what was left of the local lords, the emperor agreed to peace negotiations with the Church and relevant parties. The negotiations would take place on the journey back to Reverse where the treaty could be confirmed in the Collosius. But, before departing the emperor publically in the _Dicollossius dae Vetparis_ rejected the title which they had granted to him.",
                        "The rejection had great effect on the Mages Guild, but little effect on the EOD. As the EOD had developed into three fractionous sets of beliefs: The Emperor was the Sigmarian (the human embodiment of Sigmoria, aka God), and the Lords are his Sigmarettes; The Emperor was also the God Supreme who was Sigmaroria, who had been Sigmar and Gerald of Rivia, and the Lords are the Sigmarettes; or that the Emperor was merely a man, and the Lords were men, and the Church a separate entity from them. The first belief was common among those who were from the Milky Way, the second grew prevalent among those EOD members who had come to the Milky Way, and the Third most common among those who never visited the Milky Way.",
                        "The first two groups were able to work together to push the EOD to enshrine the first Oath to the Emperor and their Lords. Which saw the Emperor as the living embodiment of Sigmoria and the Lord Supreme, in a position equal to the Germushian Sigder, which was acceptable to both the Church of Sigmar in Germushia, and the majority of EOD members, while pleasing to the minority of survivors of the Crusade. This belief was not jostled when the Emperor and Collosius confirmed that the Versian Church Declaration had been wrong, Lords were not Sigmarettes and the Emperor was not the Sigmarian. However, the treaty did leave the door open to the interpretation that the Emperor was the Sigmarian. This overall line of thinking would be the basis for the Equites Ordinis Deorum’s Cult of the Emperor.",
                        "#### Service Till Death and the end of the Second Empire ~52556\nThe Cult of the Emperor reached its first peak at the very end of the Second Empire. The belief had become a doctrinal part of EOD teachings, the Emperor was the embodiment of the highest God, and the EOD were their servants, who depended on the Emperor for their power: political and magical.",
                        "The end of the Second Empire came during the 9th Imperial invasion of the Milky Way. During this invasion, the Trans-Galactic Empire (TGE) had exploited the internal chaos of the Federation following a series of destructive internal wars between Lords. Simiarly, the weakened Vers had only some small holdings in the Milky Way, like most of the other Great Nations. Thus the TGE assumed it would be unimpeded in its invasion of the United Federation of Earth (UFE). This belief was shattered when the UFE’s Fuhrer called on his friend and ally Empress Catharine Reverse Alluysia for assistance, and she answered by sending all Lords in the Milky Way to assist, and personally leading a large fleet of EOD members to assault the Empire.",
                        "For the Knights within the Milky Way, they began to lead wars against Imperial forces, while EOD members began battles of both blade and intellect against their Sith counterparts in the opposing Empire. Many Knights and even Lords recounted that it had been a brilliant game of interstellar Chess, let down by the ever-weak player: the UFE.",
                        "Many desperate battles and one massive fleet of Versian Lords, their Knights, and an Empress later, and a hole had been opened in the Imperial vanguard. Until then the vanguard had been scoring victory after victory against the UFE and Versian alliance. The Empress took her chance and led a fleet through the opening and into the heart of Imperial territory. While the EOD distracted the various Sith in the Area, the Empress lead her ship and a small fleet on a suicide mission into the Void-Gate. Many ships destroyed themselves by crashing into the massive ring. But the maneuver was a success. The gate was destroyed and the Imperial Fleet which was in transit and would surely have destroyed the UFE had been destroyed.",
                        "There was only one problem. The Empress was almost 5,000 years old. She had no living heirs, most had died in this war, and all who the crown could have fallen too were dead or otherwise ineligible. It was thus that for the first time in nearly 51 thousand years the Versian Empire was without emperor.",
                        "## First Republic ~52561\nThe First Republic is a highpoint of Versian society. The lack of emperor allowed Lords the ability to exercise more of their power, while self regulating into ‘fealties’ (swearing alliangce to one, essentially political factions) which governed in the Collosius. Meanwhile the thoroughly expanded empire, with many competing guilds in the Reverse galaxy, competed with each other while holdings lords and other lieges to the obligations which came with their rights. Economic prosperity brought on by the formation of the Banking Union, and eventually the Banking Guild meant far fewer wars between Lords. This period also saw a great increase in the new Titles of Lord, and the consolidation of old Titles.",
                        "Knights flourished in this age as well, though in a different manor. Gone were the days of warrior knight, instead now the purpose of a knight was to assist their lord, either in day-to-day tasks or in managing their Regalia. For the EOD they took their ability to call on other-worldly and social status as a call to serve the people, and without an emperor to build a cult around, the EOD’s religious beliefs were forced to adapt.",
                        "#### Service to Lords ~52891\nThe EOD adapted to the loss of their religious leader easily. They expanded on the idea of the Cult of Emperor, deciding that the Lords titles were the representation of one of the Gods from their Pantheon. The belief being that if the Emperor is the God Supreme, then the Lords – as the Emperors lesser but equals – must thus be the other Gods of the Pantheon. But their belief was only that the emperor was the embodiment of the God supreme, and the person themselves didn’t matter so much as the title of Emperor did. Thus, the EOD’s new belief in the idea that their Lords titles confedered the support of a god from the Pantheon. Thus, Knights would request to join the service of lords whose titles represented the Gods that those knights felt most aligned to.",
                        "It is for this reason, that the Titles represented the Gods who the Knights were believing in, that knights of the Order of the Gods devoted themselves to the service of their lords. And thus the _Oath to your highest master, the Lord (x)_ entered the cannon of EOD Oaths.",
                        "#### Devotion to the public ~54962\nSoon though, the Knights felt that devotion to their Lords alone was not enough. They could see that the empire was an organism greater then just the Lords, and their gifts had come from the Gods, but much like their title conferred service to the Lord and obligations to the people, then their service to their Lord as service to their God meant that in carrying out their feudal obligations they must also do so with their spiritual obligations.",
                        "For this reason, the EOD developed the **Oath of the Service to the Civis** and many knights turned from helping their Lords crush devils and demonic incursions, to instead using their powers to focus on dealing with inequality in the empire, bringing forth great amounts of food, fuel, or other resources as needed.",
                        "However, the monster hunting still happened, and those who took the **Oath of Protecting the Civis** become devoted members of the _Aeterna Proelais Daemes_, whose primary goal is hunting Daemons, but its generally fallen to them to deal with any otherworldly incursion. They are considered some of the top monster hunters in the Galaxy, and many Witchers take great honour on serving along side such famed warriors.",
                        "#### The deeds of Debonio; ~54,941\nDebonio; was a great Knight, and an exemplar of the period. She first entered the Knighthood transferring from the Mages guild, after spending thirty years to use her powers to help build school in rimword systems. With the extra training, knowledge, and prestige from the EOD, she was able to work out a deal with one of the Great Shipping Guilds of her day, whereupon once a week she should use her powers to produce enough food to feed a subsector in need, and the Guild would see to it that the food was delivered.",
                        "It was Debonio; who wrote the **Oath of Protecting the Civis** after helping repair a city following a meteor impact from a rogue Mage. She personally hunted down the mage and had their soul condemned to the Abyss. She then had the city issued a special charter, and a school of Mages installed whose sole job it was to protect the city from future attacks.",
                        "Debonio; was also famous for openly mocking Lords who failed to live up to their duties. Upon having dinner with Lord Pawchelerius – whose Patron god was supposedly the God of Wheat, but yet whose people had been in an expanding state of famine for nearly a century – wherein the Lord bragged about his plentiful food stores, and great amount of profit from selling excessive amounts of food, the Knight stood from the table announcing: “I would rather dine on rats with the Civis who beg outside your gates then listen to another word from the abyssal vermin who hosts this dinner”. Departing in a rush from the dinning hall, and true to her word having a meal with the starving civis beyond the moat of the Lords Castle, with food she brought forth from beyond the material world herself.",
                        "Upon another world, the Unions in service to the Nobles had gone on strike, claiming great abuses in the Noble houses. To investigate, Debonio; departed in disguise as a scab to work for the nobles. She quickly uncovered that the reports from those on strike had been but the surface, abuses of all forms were reigned down by the nobles on their servants. One day, upon a deeply dishonourable assault from a high ranking noble, Debonio; reveled who she truly was. The noble did not believe her and continued his attack. Debonio; crushed the nobles throat with her hand. She then went to the knight who governed the World and told them the whole tale. Upon discussion between the two, they agreed a new cast of nobility was needed, and granted numerous titles which once belonged to the vile nobles to the leaders of the Unions, and thus both they and their Unions were happy.",
                        "Debonio; was no stranger to the issues of religion either, she was a key member in settling the Mages Guild’s internal dispute about the nature of Sigmoria in the absence of the emperor. Her conclusion was that the emperor was not truly gone, simply gone from the eyes of the Empire. While it failed at settling the dispute, it was a core argument in the winning camps overall argument.",
                        "Thus,  it is that Debonio; was an exquisite example of an Equites from her age, working to advance the cause of the people, even in the face of previous oaths to the Lords, and unintentionally laying the groundwork for the eventual return of the royal family, and restoration of the Versian Empire.",
                        "",
                        "",
                        "",
                        "",

                    }),
                    new InformationSection("Order Beliefs",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Major Oaths",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Schools of Magic",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Relation to other Orders",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Relation to Other Guilds",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Standing in Versian Society",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Notable Members",new List<string>()
                    {
                        ""
                    }),
                    new InformationSection("Important Points",new List<string>()
                    {
                        ""
                    }),
                }),
        };
    }
}