using System.Collections.Generic;

namespace TravellerWikiInfomationArticles.Articles
{
    class VersianGender
    {
        public static InformationArticle GetArticle() =>
            new InformationArticle(
                "Versian Gender",
                "The Versian concept of gender is different the current or modern concept of gender, which is more akin to that of the United Federation of Earth. The largest two differences are: that Versian Gender is completely divorced from biological sex in any way, and that Versian gender is extremely fluid - to the point where someones gender may change during a conversation. This is because Versian gender is based on ones current actions, and the motive behind them. As such, the Masculine gender is generally noted for being active, and dominant, while the feminine gender is noted for being passive and submissive. " +
                $"However, it should be **stressed** that this is based on ones current actions, not on any deterministic train of ones biological sex. As due to advanced genetic modification biological sex, like biological race, eye colour, hair colour, or other physical traints are completely open to remodeling. This practice is especially prominent among [Versian Aristocratics]({WikiInformationArticles.GetArticleLinkIDByName("Versian Aristocratics")}) as an expression of their wealth",
                new List<InformationSection>()
                {
                    new InformationSection("Basic's of Versian Gender", new List<string>()
                    {
                        "The modern Versian concept of gender is extremely fluid, and based on one’s current actions, and the motivation behind them. Within Versian society, the Masculine gender is regarded as the active or dominant gender in a situation. More specifically, one is considered Masculine if one is doing something of their own volition, or to suit their own goals. The Feminine gender is regarded as the passive, or submissive gender in a situation. More specifically, one is considered Feminine if they are doing something on behalf of another, or to forward someone else’s goal. ",
                        "For example, a Knight hunting pirates in their system is masculine, because they are choosing to deal with the pirates of their own volition. While a Knight fighting for their Lord is considered feminine as they are fighting to advance their Lords goals. Generally, a good solider is considered Feminine, while a bad solider is considered masculine. A stay-at-home father would be feminine, while a working mom is masculine.",
                        "As previously said, Versian Gender is quite fluid. A student may well be masculine while at home watching TV and eating cereal, but become feminine while receiving instruction in school, only to revert to masculine during recesses as the head of their peer group, while the rest of their peers remain feminine.  Over the course of a conversation a Knight may go from masculine to feminine and back again as their Lord makes their mind up about what to do.",
                        "Further complicating matters is that Gender and legal status are closely intermingled. This is because **all** rights are defined by a feudal contract. The person fulfilling a feudal obligation is considered masculine (as they have chosen to follow through on the obligation and are thus active) and the one calling for the obligation to be fulfilled is feminine (as they have chosen to call on someone else, and thus are passive). But when one is calling on a right from the feudal liege, they are considered feminine as they are being submissive to their feudal master, and the one fulfilling the called-on right is considered male as they are the active, dominant force being called on to enforce the right.",
                        "An implication of Gender related rights is that some rights depend on the Gender of an action. For example, it is against the law for any other man/masculine person to enter the Master of a House’s inner-sanctum, however women/feminine people are granted the right to be invited into the sanctum. This is because to overthrow your Master is an Active/Male gender trait, so anyone doing such an action in their Master’s office are given another reason to be charged, while also granting the feudal Master an even higher degree of power over their subject while also reenforcing the power differential between Master and Subject.",
                        "A further aspect of Gender in the Vers Empire is how Gender relates to Honour and Glory. Honour is considered masculine in Versian society, as in Versian culture it is believed that one Gains Honour from *their* actions. While honour is shared among one’s family, title, and self, honour itself is only gained for all of those things through one’s own actions. Thus, because honour is something one goes and gains for themselves in Versian Society, it is considered masculine. Glory is considered feminine in Versian society because glory is earned. What that tends to mean to Versians is that one earns glory in the service of their master, and because it is gained as part of service to their master, it is feminine. Thus, it is glorious women who are great inventors and form the basis of awesome tales, but honourable men who found companies or lead armies.",
                        "This has practical affects in the language used by Knight to Soldier vs a Lord to their Knight. A Knight calls on their troops to fight for glory, while a Lord asks their Knights to join them in battle for honour.",
                    }),
                    new InformationSection("History of Versian Gender", new List<string>()
                    {
                        "#### First Empire – Foundation of Gender Norms\nWhen the Vers Empire was first founded, the 21st century concept of gender was still around, though greatly diminished. The demands of life on the terraforming Red Rock allowed for many of the Versian upper class to ditch gender entirely. This led to a redefinition of gender as an aspect of class in social relations, completely divorced from the concept of biological sex.  Essentially, by the rich identifying as genderless, gender was left to the ‘poors’. Due to the ‘poors’ social status, many of the gender norms which previously were associated with women became associated simply with not being in the elite, which in turn codified what might have been considered masculine into the elite.",
                        "But as feudal relationships developed and various elites developed an interconnected relationships with one another, and the ‘poors’ developed similar hierarchies, the border of gender shifted again based on the new power dynamics. Wherein the Elite/Male gender became associated with holding power or control, while the Poor/Feminine became associated with having to defer to those with power.",
                        "As a result of this, regardless of the current sex of the Emperor, they were always titled Emperor, as they were the sole source of power, from which all other power radiated down. Thus, in the Collosius, there is only one man.  While in a Lords regalia, they are the sole source of power, and so in their court there is only one man, but when the Lords are with their peers, and the Emperor is not around, then there are men, but through social and feudal relationships the some of those lords may well have been women in the eyes of the room. However, should one of a lower social class enter the room, then all those of the superior social class are to be treated as men. While the lower social class person as a woman.",
                        "Again, it should be stressed that in the First Empire, **gender became completely divorced of biological sex** – which itself due to genetic augmentation became completely meaningless – and **instead it came to be entirely associated with being an expression of power in a conversation.**",
                        "#### Second Empire – Gender takes on Honour\nWhen the Second Empire took form, one of its distinguishing features from the First Empire was that of a renewed focus on personal Honour. To be like the lazy Elites who refused to work and who had power taken from them took on being feminine. Going out and working for the empire, working for yourself, working to advance yourself and the Empire became honourable, and honour became a socially understood way to communicate power.",
                        "With the feudal structure, one was locked into power by class, but within that class it came down to social relationships. Honour became a way to encode those social relationships and transmit with them a degree of power. However, honour became associated as a masculine trait, with a relative association with power, so that to be honourable was to have power, but more importantly to have that power because you worked for it, and work to maintain it, and that work is acknowledge by the greater society.",
                        "An attack on one’s honour became equal to an attack on ones power and manliness. To lack power was to be a Civis, but to lack honour made one a woman in Versian society. Thus one could have power and still be a woman. To be a man meant power and honour. But honour was available to all classes, and those who worked towards gaining honour were often able to achieve it. An especially potent vehicle for this was joining the militorius, and soon military service became a quick and effective path to honour. While serving in the administration became seen as dishonourable, willing to only do minimal work but not the *real hard work* of the military.",
                        "#### First Republic – Genders take on Legal Meanings\nIn the First Republic gender underwent another shift, as it became associated with certain legal rights. Through honour it became dishonourable to have to request for help from another, thus those who had to call on their legal rights were seen as being in a dishonourable position, and in a vulnerable position and so without power. In this situation, the person thus became feminine once again. As a result of this, to enforce one’s rights, actively work to make sure your rights were being upheld, etc, were seen as honourable. While being unable to have your rights enforced, having to appeal to a superior to enforce your rights, etc, became associated with being feminine. ",
                        "As a result of this time, many feudal relationships developed into feminine forms, and guilds became very feminine organizations in Versian culture. While being on your own, asserting your rights, and especially being at the top of a hierarchy became associated with masculinity. The head of the family was now the head of the hierarchy, and thus masculine, and as an extension they were honourable and had power of the household. However, due to the general fluidity of relationships within households – and job markets – the head of the household often changed, reenforcing the overall fluid nature of gender in the Versian culture.",
                        "#### Third Empire – Gender becomes infused with Glory\nThe Third Empire brought many changes, the largest being the introduction of the Sith, and the introduction of the Sith concept of Glory. Versian society had always viewed glory as the same thing as honour, but Imperial society viewed Glory in a different light. Imperial society saw glory as being something which was gained through service. This comes from key differences in internal culture, where Versian society is an Empire of united fiefdoms, Imperial society is a singular monolithic entity lording over the whole of the empires land, managed by a changing cast of pieces in the imperial machine. Essentially, in Versian society you served your family first, your immediate master second, their master third, your lord forth and the empire fifth. In Imperial society you served yourself first, the empire second, and your family third.",
                        "In Imperial society one earned Glory through service to the Empire, this translated into Versian society as one could earn Glory through service to their master. Thus feminists in the Versian empire began a long campaign of associating Glory with feminimity and Glory as a positive alternative to honour.",
                        "Their great success was in embedding the idea of a good solider being a woman, as it is glorious to fight for ones Knight and Lord, to take orders and die for the greater Empire, and yet men could distinguish themselves with honour, allowing for a clear class separation and by extension social understand to develop between the glorious infantrymen and the honourable officers who commanded them.",
                        "This proved to be a successful and symbiotic relationship. While it reenforced power and the idea of male superiority in the empire, it granted those who were in the subservient gender a way to continue to earn respect. This respect in turn allowed for an expansion of the legal rights of women, as many knights who earned their title had done so through glorious service of some kind until they were able to gain honour. They relied on that glory is their feudal relationships with their peers and superiors, and so they were unable to deny it outright to the Civis who claimed it as well.",
                        "#### Post great war developments into the Fifth Empire\nFollowing the Great War, the returning soldiers were filled with Glory, and many Knights and their families had gained large amounts of honour in the Great War. The glorious soldiers returned home to the post war economic bubble, and in turn were able to start small personal businesses’ which ballooned in value making them rich overnight. Because money and power had been closely interconnected in the empire, money had always had a deep connection to honour. Thus, many of these glorious soldiers who had struck it rich began to demand honour. Many demanded minor noble titles from their Knight’s saying their glorious service entitled them to these honours. A benefit of gaining the title was that the soldiers could formally turn their capital into power and by extension expand their personal and familial honour.",
                        "But when the bubble popped, those same people clambering for titles fell deeply into debt, something which was considered dishonourable. Attempts to appeal to their glory fell of deaf ears, surmised as one Knight famously said: “You pleaded that I convert your glory to honour, I listened. Now you cry at my feet, demanding I restore your glory – but I can grant only pity.” ",
                        "Their anger was targeted towards those who had seceded from the empire by Emperor Charles with the promise of Glory and Honour to be gained from reuniting the empire. When the Third Republic informally took over governing from the restored Emperor Henry and signed the treaties ending the war, the soldiers who had made it into what was left of the Empire felt as though they had gained no glory, and certainly no honour. ",
                        "The civil unrest of the Third Republic certainly didn’t help those who in the Militorius. Its hard to think you’re glorious for defending your Lord from a hoard of starving peasants, especially when the people you love may well be in that hoard. Mass desertions became common. A similar trend appeared in the Mages Guild, who had retreated into their literal ivory towers, temples, and universities. Many within were disgusted by the state of the empire, and left the Mages Guild to form cults of their own, attempting to carve out their own little bastions of power, and asserting themselves as honourable.",
                        "With the dawn of the Fifth Empire, Honour and Glory have seemingly taken on new meanings. Glory now is to serve your family first, the Empire and its people second, your Lord third and yourself last. Honour means protecting the weak and helping the glorious, it still means having power, but it also means using that power for the greater good of the Empire over yourself. You may gain honour from personal actions done of your own accord, but it is only honourable if others see you do it, and you’re doing it in service of the Empire and its people.",
                        "By extension, the ideas of genders have taken on these concepts, women still refers to the person who lacks power in a relationship, but glory has expanded in meaning and purpose to match changes for what honour means. At the same time, honourable men are required to hold power to be men and thus have access to honour at all. However, because power is fluid and changing depending on the circumstance and moment, gender is still not a set thing for any given person and depends on the circumstances, but in the Fifth Empire, neither gender is truly inferior to one another, simply focused on different areas, a symbiotic relationship reflective of the outlook of the Fifth Empire, a hope to form a symbiotic relationship out of the First Republic and Third Empire. ",
                    }),
                    new InformationSection("Interesting Facts", new List<string>()
                    {
                        
                    }),
                    
                });
    }
}